

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
      - "50051:50051"
    restart: on-failure
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      DEFAULT_VECTORIZER_MODULE: 'none'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'weaviate'

volumes:
  weaviate_data:
